# Generated by Django 3.2 on 2022-01-31 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nascimento',
            field=models.DateField(null=True),
        ),
    ]
