# Generated by Django 3.2 on 2022-02-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='nascimento',
        ),
    ]
