# Generated by Django 3.2 on 2022-02-03 22:33

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hobbies',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/man.png', null=True, upload_to=blog.models.upload_to, verbose_name='Image'),
        ),
    ]
